### ISSUE TITLE
search bar on the site

### ISSUE THREAD

**Issue by thomas-saigre** [feelpp/book.feelpp.org#113]
It could be very useful to have a search bar if we look for a particular notion and don't really know in which page it is

**Comment by prudhomm** [comment]
it is available on the top navbar. you may need to hard refresh the web page to see it. I use Algolia to index the website. the index is organized by antora components and version for feelpp dependent components and are versionless for the others (version is set to _master_ in that case as defined by antora).

<img width="1678" alt="Screenshot 2020-04-17 08 25 28" src="https://user-images.githubusercontent.com/151693/79538644-0a4c4e00-8085-11ea-8b23-9900445e63c9.png">
