### ISSUE TITLE
Python page doesn't not print the examples

### ISSUE THREAD

**Issue by ValletRomain** [feelpp/book.feelpp.org#153]
Hello, the pages of folder `book.feelpp.org/docs/user/modules/python/pages` do not print the test code in `book.feelpp.org/docs/user/modules/python/examples/python`. I think, is a problem of path.

**Comment by Trophime** [comment]
The path of the included source python scripts are no longer valid; e.g.: `include::{uri-pyfeelpp-raw}core/test_core.py[]`

**Comment by prudhomm** [comment]
@thomas-saigre the issue should be clsoed no ?

**Comment by thomas-saigre** [comment]
there is still an issue I didn't manage to fix when I looked in the Feel++ Toolboxes in Python section : see for instance [this page](https://docs.feelpp.org/user/0.109/python/pyfeelpptoolboxes/heat.html) where the example of `fluid` is displayed

**Comment by thomas-saigre** [comment]
I just saw that issue #107 already refers to this problem, so yes this issue can be closed
