### ISSUE TITLE
Typing mistake & broken link

### ISSUE THREAD

**Issue by PhilippeRicka** [feelpp/book.feelpp.org#17]
In user manual , [12.9 Strong Formulation](http://book.feelpp.org/user-manual/#strongform), I think integral signs have to be removed in the second equation.
Also, the link in [12.7 to advanced informations about function spaces](http://book.feelpp.org/user-manual/#spaces_and_elements) seems to be broken.

**Comment by prudhomm** [comment]
@PhilippeRicka it could be interesting that you make the correction for the book ;)
let's meet to discuss that. it is a good exercise

**Comment by prudhomm** [comment]
This has been fixed in 0.104
