### ISSUE TITLE
Add postprocessing section documentation

### ISSUE THREAD

**Issue by gdolle** [feelpp/book.feelpp.org#28]
We should add a section to explain how to post process data with feel++ (basics, + ref to paraview, gmsh, ... doc)

In particular, how to use
- paraview Insitu with feel++
- paraview pvserver
- paraweb (later)
- gmsh

etc...

**Comment by gdolle** [comment]
We can use MSO4SC D4.1 section 9.4 for this issue.

**Comment by prudhomm** [comment]
What do you mean? We do not describe exporter or any technical details  about post processing there?

**Comment by gdolle** [comment]
Ok I thought that we would add a paragraph relative to paraweb in it later.

**Comment by prudhomm** [comment]
Right there is the user Manual and the programming manual. What you propose would go into the user manual? That's a good idea

**Comment by prudhomm** [comment]
@gdolle any update on this?

**Comment by prudhomm** [comment]
see https://github.com/feelpp/book.feelpp.org/tree/wahl-patch1
