### ISSUE TITLE
Add page on Feel++ installation on supercomputer !

### ISSUE THREAD

**Issue by prudhomm** [feelpp/book.feelpp.org#4]
tentative title : Feel++ for HPC centers

 - [ ] Atlas port
 - [ ] Strasbourg Mesocentre

**Comment by Trophime** [comment]
As far as I know in Grenoble Mesocentre they have switched to Nix packages instead of modules (maybe @metivett can confirm).

The port for Grenoble would be then very specific. The best will certainly be to create a feelpp nix package.. Would do you think?

**Comment by prudhomm** [comment]
@gdolle news on this one ?
I saw also that the wiki on atlas got moved, I wanted to include it in this page and maintain, now it is on the wiki of the lab.

**Comment by prudhomm** [comment]
@gdolle @vincentchabannes what are the news on this page ? it would nice to add Atlas too

**Comment by gdolle** [comment]
I'll do it today.

**Comment by prudhomm** [comment]
there are various machines, We need to have some kind of template with, as a priority, the machines that are most used. the urgency is on pch however ;)

**Comment by prudhomm** [comment]
@PhilippeRicka will need also these informations to work on Altas

**Comment by prudhomm** [comment]
@gdolle have you started the page ? do you want me to start the page ?

**Comment by gdolle** [comment]
Yes I'have started already, I'll PR soon

**Comment by prudhomm** [comment]
@gdolle  what is the state of these documentations? I guess that on Atlas and Alsacalcul are up to date

**Comment by prudhomm** [comment]
@gdolle it was said in April 2017 that there was going to be a PR soon ? what is the status ?
