### ISSUE TITLE
Add documentation to use Feel++ Alsacalcul

### ISSUE THREAD

**Issue by prudhomm** [feelpp/book.feelpp.org#49]
It is now strategic to document the use of Feel++ on Alsacalcul and verify that Feel++/singularity is working there properly.  

We would like to provide Feel++ services on Alsacalcul first the standard way, then the MSO4SC way once it is stable enough

/cc @vincentchabannes  @gdolle

**Comment by prudhomm** [comment]
the online page is here http://docs.feelpp.org/docs/stable/infra/alsacalcul/, and the source is here
https://github.com/feelpp/book.feelpp.org/tree/feature/antora/docs/docs/modules/ROOT/pages/infra
we want to make sure that we add a message to companies/enterprises eg here
https://github.com/feelpp/book.feelpp.org/blob/feature/antora/docs/docs/modules/ROOT/pages/index.adoc#infrastructure

**Comment by gdolle** [comment]
It's weird. The cluster is not called AlsaCalcul is it ? I would prefer mesocentre of Strasbourg or mesostra.

**Comment by gdolle** [comment]
Ok. For what I understood me AlsaCalcul was the service which should by Cemosis now. And the "mesocentre de Strasbourg" is actually the known name for the infra used by both. 
In the docs it's confusing... But ok.

**Comment by prudhomm** [comment]
nope that was **Alsacalcul Services** that was integrated into Cemosis. but may @celineCQ  can comment on that ;)

**Comment by prudhomm** [comment]
and by the way mesocentre does not translate well to english

**Comment by prudhomm** [comment]
Why is it closed? Were any commit associated? If yes then in the future add the #<issue id> in the commit log to make the link

**Comment by prudhomm** [comment]
should this issue be closed now ?

**Comment by gdolle** [comment]
It's up to date, but I think we can keep it open, it still need to be polished (I'm testing singularity currently with the help of D Brusson on the machine.)

**Comment by prudhomm** [comment]
Thanks. I will close the issue. I want to make the release. We will create new issues as needed to follow more precisely the singularity evolution.
