### ISSUE TITLE
Add journaling/benchmarking documentation

### ISSUE THREAD

**Issue by prudhomm** [feelpp/book.feelpp.org#50]
it would be nice to have the description of the benchmark framework in the dev manual http://docs.feelpp.org/dev/0.1 (a new module of course). We could have also a section also in the user manual to explain how to produce the Feel++ simulation journal

**Comment by prudhomm** [comment]
@gdolle you could work in tandem with @celineCQ  to write the documentation. 
The documentation should be split into the user and dev manuals and possibly the toolboxes manual ( need to discuss this with @vincentchabannes )

**Comment by gdolle** [comment]
Yes ok. 

Just to precise the goal. There are two level of documentation.
- The dev manual will introduce how the core of the benchmark system, and how to add new class in the system.
- The toolbox/user documentation will be how to view, feed the journal (It MUST be simpler than the dev one).

**Comment by prudhomm** [comment]
I move the issue to v0.105

**Comment by prudhomm** [comment]
any idea when it is available? We have to start the last deliverable for WP4 soon and this will need to be delivered.

**Comment by gdolle** [comment]
No idea yet, too overwhelmed currently.
When is WP4 deadline? I will focus on the doc probably after PDESoft for a doc ready for ECMI. If we do a mso4sc sprint first week of June, this can be added to the sprint.

**Comment by prudhomm** [comment]
@gdolle what is the current status of the documentation ?
