### ISSUE TITLE
Document Feel++ data management plan 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/book.feelpp.org#51]
The Feel++ data management needs to be documented and should be available online in the feelpp books/docs.

* A first idea: create a  module that should appear in the user, dev and toolbox manuals and contain the overall strategy.
* A second idea: split the management plan between user, dev and toolbox manuals

what do you think? 
I would prefer a overall picture in one module

**Comment by prudhomm** [comment]
@Trophime @jbwahl @mszopos @lsala this impacts also eye2brain and hifimagnet which also need to have a similar task in their respective projets

**Comment by Trophime** [comment]
Is there already some plans for this **Feel++ data management** ?

This is important to have some hints in order to decide which organization in the docs shall be privileged.

**Comment by prudhomm** [comment]
@trophime, @vincentchabannes is working on a first draft based on recent discussions and our recent work in this area. Please jump in to give your feedback and thoughts on the subject

**Comment by prudhomm** [comment]
@vincentchabannes @gdolle  shouldn't the file be split into different sections,
and have the navigation reflect that?

**Comment by prudhomm** [comment]
And how about having a feel++ data manual like the user and development manual?

**Comment by gdolle** [comment]
@prudhomm I think that would be nice. :+1:

**Comment by prudhomm** [comment]
so as mentioned earlier I think we have enough material to have our own Data Manual
