### ISSUE TITLE
Provide various version of the manuals cover image

### ISSUE THREAD

**Issue by prudhomm** [feelpp/book.feelpp.org#6]
- Feel++ User Manual
 - Feel++ Programming Manual
 - Feel++ FEM Manual
 -  Feel++ HDG Manual
 - Feel++ RBM Manual 

wouk it be possible to do it by script ?

**Comment by prudhomm** [comment]
do you think it is doable ?

**Comment by gdolle** [comment]
Yes I think it's doable. I was thinking to generate an svg cover via javascript per book.

**Comment by prudhomm** [comment]
on cell phones and tablets it does not look good
