### ISSUE TITLE
Documentation FSI

### ISSUE THREAD

**Issue by lberti** [feelpp/book.feelpp.org#67]
I can't find the FSI toolbox documentation explaining the various possible options that one can choose, (neither in books nor in docs)

**Comment by prudhomm** [comment]
@lberti any news on this one? Do you need some guidance?

**Comment by lberti** [comment]
Yes, please. I have now access to the FSI folder.

**Comment by lberti** [comment]
If you want me to write the documentation, could you please give me the articles to read? This issue was linked to a problem I had with the simulations that now is solved

**Comment by prudhomm** [comment]
Sure I will upload that to asana. However are for example the current different ways to reconstruct the Ale map documented? eg Winslow... From @vincentchabannes thesis

**Comment by lberti** [comment]
In @vincentchabannes thesis there are the different ways to reconstruct the Ale map (Harmonic extension, Harmonic extension modified and Winslow), but I don't see them in the Theory section of the Fsi manual. 
I am not sure I understand what you mean by schemes/strategies. Do you mean partitioned vs monolithic? Or the analytical expression of the coupling conditions? Or Neumann-Dirichlet and Robin-Robin? This latter only is present in the Discretization and Coupling Strategies sections of the Fsi Theory manual, and it is very briefly explained

**Comment by lberti** [comment]
I have written a brief page on the FSI coupling conditions, based on the articles that I have received. Where can I put it, so that you can give me a feedback about it?

**Comment by vincentchabannes** [comment]
@lberti you can put the doc in ```docs/toolboxes/modules/fsi/pages/theory.adoc```

**Comment by lberti** [comment]
Do I have to create a branch or can I submit to the branch feature/antora directly from the webpage by copy pasting my contribution to the end of the file?

**Comment by prudhomm** [comment]
Create a branch issue-67-fsi-theory
