### ISSUE TITLE
Add images for HDG toolboxes

### ISSUE THREAD

**Issue by prudhomm** [feelpp/book.feelpp.org#7]
List the hdg toolboxes and present them like the other toolboxes

**Comment by prudhomm** [comment]
@romainhild @lsala has everything been moved to http://book.feelpp.org ? or are there still some bits ?

**Comment by prudhomm** [comment]
We should get help from @gdolle on this to setup the environment

**Comment by prudhomm** [comment]
@lsala I propose to use
 - a _red_ case image to illustrate the HDG darcy toolbox with both scalar and flux fields
 - a cantilever for mixed elasticity such as the one where you apply ibc
what do you think?

then the idea is to have these on this page: http://docs.feelpp.org/toolboxes/0.106/

**Comment by lsala** [comment]
Ok, where can I send you/put the images? One and one right?

**Comment by prudhomm** [comment]
upload them with the other one of the toolboxes, have a look at the resolution/size of the other ones for the toolboxes

**Comment by prudhomm** [comment]
they are here : https://github.com/feelpp/book.feelpp.org/tree/master/docs/toolboxes/modules/ROOT/assets/images
